module.exports = [
    {
        "url": "https://api.github.com/repos/att/rcloud/issues/comments/436994840",
        "html_url": "https://github.com/att/rcloud/issues/2617#issuecomment-436994840",
        "issue_url": "https://api.github.com/repos/att/rcloud/issues/2617",
        "id": 436994840,
        "node_id": "MDEyOklzc3VlQ29tbWVudDQzNjk5NDg0MA==",
        "user": {
        "login": "gordonwoodhull",
        "id": 1366709,
        "node_id": "MDQ6VXNlcjEzNjY3MDk=",
        "avatar_url": "https://avatars2.githubusercontent.com/u/1366709?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/gordonwoodhull",
        "html_url": "https://github.com/gordonwoodhull",
        "followers_url": "https://api.github.com/users/gordonwoodhull/followers",
        "following_url": "https://api.github.com/users/gordonwoodhull/following{/other_user}",
        "gists_url": "https://api.github.com/users/gordonwoodhull/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/gordonwoodhull/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/gordonwoodhull/subscriptions",
        "organizations_url": "https://api.github.com/users/gordonwoodhull/orgs",
        "repos_url": "https://api.github.com/users/gordonwoodhull/repos",
        "events_url": "https://api.github.com/users/gordonwoodhull/events{/privacy}",
        "received_events_url": "https://api.github.com/users/gordonwoodhull/received_events",
        "type": "User",
        "site_admin": false
        },
        "created_at": "2018-11-08T13:33:28Z",
        "updated_at": "2018-11-08T13:33:28Z",
        "author_association": "MEMBER",
        "body": "We got a similar error a very long time ago in #701 - looks like it may be the same cause, notebook with same name as notebook folder. (FWIW this time the offending notebook was not starred, so I only saw it in All Notebooks, not Notebooks I Starred.)"
        }
]